### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by Marzal** [okkur/website#21]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
https://about.okkur.org/syna is outdated

**What you expected to happen**:
Documentation should be updated

**How to reproduce it (as minimally and precisely as possible)**:
check https://about.okkur.org/syna  against exampleDir

**Anything else we need to know?**:
https://github.com/okkur/website/tree/master/content/syna

Happy new year :smile:

**Comment by stp-ip** [comment]
That slipped through. In theory this could be done with a PR, but will do my best to get this updated on my side.

For reference:
https://github.com/okkur/website/tree/master/content/syna

Basically the subdirectory `syna` is a copy of the exampleDir with the manual changes noted down in the readme. Website deploy is automated after a PR is merged :)

**Comment by stp-ip** [comment]
Sidenote: We do have an autodeployed "demo" version, which is always up to date with the documentation from master: https://syna-demo.okkur.org/

**Comment by Marzal** [comment]
> That slipped through. In theory this could be done with a PR, but will do my best to get this updated on my side.
> 
> For reference:
> https://github.com/okkur/website/tree/master/content/syna
> 
> Basically the subdirectory `syna` is a copy of the exampleDir with the manual changes noted down in the readme. Website deploy is automated after a PR is merged :)

I didn't fully understand the manual changes (and also I'm a bit shot on time), I would watch the next commit to get a whole idea of every change needed :eyes:

**Comment by stp-ip** [comment]
Should be done in the next couple of days. ;)

**Comment by stp-ip** [comment]
Took a bit longer, but now the page is up to date. \o/
