### ISSUE TITLE
Wrong link to Fragments

### ISSUE THREAD

**Issue by nitmws** [okkur/website#9]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
In https://about.okkur.org/syna/docs/fragments/#built-in-fragments clicking on the link of "... in the **fragments** section." does not show the fragments section.

**What you expected to happen**:
To be linked/forwarded to https://about.okkur.org/syna/fragments/

**How to reproduce it (as minimally and precisely as possible)**:
Click on the link described above.

**Anything else we need to know?**:

**Environment**:
- Okkur Labs Website version:  latest (on 2019-07-25)
- Others:

**Comment by stp-ip** [comment]
Thanks for the report. Will see to get this fixed.

**Comment by mpourismaiel** [comment]
This linking in the file seems to be okay. I think something has changed in the build time.

![image](https://user-images.githubusercontent.com/14017717/61876013-1abe0680-af01-11e9-972a-9356d5e42a1d.png)

**Comment by stp-ip** [comment]
The okkur website pulls in the syna exampleSite, which breaks a few things from time to time. Seems like this also broke. Another issue https://github.com/okkur/syna/pull/576
